name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main   # ou master selon ta branche par défaut

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # ou ta version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx-rtd-theme  # si tu veux un thème sympa
          # pip install -r requirements.txt  # si tu as un fichier requirements pour la doc

      - name: Build HTML
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
